# Generated by Django 6.0.3 on 2026-05-08 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croppredictionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crop Prediction History', 'verbose_name_plural': 'Crop Prediction Histories'},
        ),
        migrations.AddField(
            model_name='croppredictionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='croppredictionhistory',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], db_index=True, default='farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='croppredictionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='croppredictionhistory',
            name='ph',
            field=models.FloatField(verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='croppredictionhistory',
            name='predicted_crop',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Ginger', 'Ginger'), ('Gram', 'Gram'), ('Grapes', 'Grapes'), ('Groundnut', 'Groundnut'), ('Jowar', 'Jowar'), ('Maize', 'Maize'), ('Masoor', 'Masoor'), ('Moong', 'Moong'), ('Rice', 'Rice'), ('Soybean', 'Soybean'), ('Sugarcane', 'Sugarcane'), ('Tur', 'Tur'), ('Turmeric', 'Turmeric'), ('Urad', 'Urad'), ('Wheat', 'Wheat')], db_index=True, default='Rice', max_length=100),
        ),
        migrations.AlterField(
            model_name='croppredictionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['user'], name='crop_croppr_user_id_1827e3_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['user_type'], name='crop_croppr_user_ty_c46b82_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['predicted_crop'], name='crop_croppr_predict_c84efa_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['created_at'], name='crop_croppr_created_49decb_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['updated_at'], name='crop_croppr_updated_15687b_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['user', 'created_at'], name='crop_croppr_user_id_f3ee4c_idx'),
        ),
        migrations.AddIndex(
            model_name='croppredictionhistory',
            index=models.Index(fields=['user_type', 'predicted_crop'], name='crop_croppr_user_ty_043047_idx'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('nitrogen__gte', 0)), name='crop_prediction_nitrogen_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('phosphorus__gte', 0)), name='crop_prediction_phosphorus_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('potassium__gte', 0)), name='crop_prediction_potassium_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('temperature__gte', -50), ('temperature__lte', 100)), name='crop_prediction_temperature_valid'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('humidity__gte', 0), ('humidity__lte', 100)), name='crop_prediction_humidity_valid'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('ph__gte', 0), ('ph__lte', 14)), name='crop_prediction_ph_valid'),
        ),
        migrations.AddConstraint(
            model_name='croppredictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('rainfall__gte', 0)), name='crop_prediction_rainfall_gte_0'),
        ),
    ]
