# Generated by Django 6.0.3 on 2026-06-04 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], db_index=True, default='farmer', max_length=20)),
                ('message', models.TextField(verbose_name='User Message')),
                ('bot_response', models.TextField(blank=True, null=True, verbose_name='Bot Response')),
                ('has_image', models.BooleanField(default=False)),
                ('has_pdf', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Conversation',
                'verbose_name_plural': 'Chatbot Conversations',
                'db_table': 'chatbot_conversation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='chatbot_con_user_id_81f32d_idx'), models.Index(fields=['user_type'], name='chatbot_con_user_ty_bbefdb_idx'), models.Index(fields=['status'], name='chatbot_con_status_f0d240_idx'), models.Index(fields=['created_at'], name='chatbot_con_created_e6d9d9_idx'), models.Index(fields=['user', 'created_at'], name='chatbot_con_user_id_6aaf26_idx')],
            },
        ),
    ]
