# Generated by Django 6.0.3 on 2026-06-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pestprediction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pest Prediction', 'verbose_name_plural': 'Pest Predictions'},
        ),
        migrations.AddField(
            model_name='pestprediction',
            name='severity',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNCLEAR', 'Unclear')], default='UNCLEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='pestprediction',
            name='top_predictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pestprediction',
            name='treatment_priority',
            field=models.CharField(blank=True, default='Upload Clear Image Again', max_length=100),
        ),
        migrations.AddField(
            model_name='pestprediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pestprediction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pestprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['status'], name='pest_detect_status_8c8bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['pest_name'], name='pest_detect_pest_na_774b75_idx'),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['confidence'], name='pest_detect_confide_47e361_idx'),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['severity'], name='pest_detect_severit_027901_idx'),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['created_at'], name='pest_detect_created_f49c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='pestprediction',
            index=models.Index(fields=['user', 'status'], name='pest_detect_user_id_b0e6a8_idx'),
        ),
    ]
