# Generated by Django 6.0.3 on 2026-04-11 09:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Equipment name can contain letters, numbers, spaces, hyphen, &, (), / and dot only.', regex='^[A-Za-z0-9\\s\\-\\&\\(\\)\\/\\.]+$')])),
                ('equipment_code', models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Equipment code must contain only uppercase letters, numbers, underscore, or hyphen.', regex='^[A-Z0-9_-]+$')])),
                ('equipment_slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('equipment_category', models.CharField(max_length=100)),
                ('equipment_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_description', models.TextField(blank=True, null=True)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_image', models.ImageField(blank=True, null=True, upload_to='equipment/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('equipment_status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment_code'], name='equipment_r_equipme_6ef4ee_idx'), models.Index(fields=['equipment_slug'], name='equipment_r_equipme_a935f1_idx'), models.Index(fields=['equipment_category'], name='equipment_r_equipme_acaaaf_idx'), models.Index(fields=['equipment_brand'], name='equipment_r_equipme_64f729_idx'), models.Index(fields=['equipment_status'], name='equipment_r_equipme_bd65aa_idx'), models.Index(fields=['is_active'], name='equipment_r_is_acti_38d99f_idx'), models.Index(fields=['location_city'], name='equipment_r_locatio_63d86c_idx'), models.Index(fields=['created_at'], name='equipment_r_created_184461_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rental_price_per_day__gte', 0)), name='equipment_rental_price_per_day_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Booking code must contain only uppercase letters, numbers, underscore, or hyphen.', regex='^[A-Z0-9_-]+$')])),
                ('booking_slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('customer_full_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Customer full name can contain letters and spaces only.', regex='^[A-Za-z\\s]+$')])),
                ('customer_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^[0-9+\\- ]{8,15}$')])),
                ('customer_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_full_address', models.TextField(blank=True, null=True)),
                ('booking_created_date', models.DateField()),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('booking_total_days', models.PositiveIntegerField(default=0)),
                ('booking_rental_price_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to='equipment_rental.equipment')),
                ('farmer_user', models.ForeignKey(limit_choices_to={'user_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Booking',
                'verbose_name_plural': 'Equipment Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_code'], name='equipment_r_booking_99541e_idx'), models.Index(fields=['booking_slug'], name='equipment_r_booking_fc81d8_idx'), models.Index(fields=['farmer_user'], name='equipment_r_farmer__f1e16f_idx'), models.Index(fields=['equipment'], name='equipment_r_equipme_413e79_idx'), models.Index(fields=['customer_full_name'], name='equipment_r_custome_fe47d9_idx'), models.Index(fields=['customer_phone_number'], name='equipment_r_custome_764370_idx'), models.Index(fields=['booking_created_date'], name='equipment_r_booking_f51dff_idx'), models.Index(fields=['booking_start_date'], name='equipment_r_booking_7f809d_idx'), models.Index(fields=['booking_end_date'], name='equipment_r_booking_d9deb4_idx'), models.Index(fields=['payment_status'], name='equipment_r_payment_d1571b_idx'), models.Index(fields=['booking_status'], name='equipment_r_booking_1cc2a1_idx'), models.Index(fields=['created_at'], name='equipment_r_created_48b871_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('booking_total_days__gte', 0)), name='booking_total_days_gte_zero'), models.CheckConstraint(condition=models.Q(('booking_rental_price_per_day__gte', 0)), name='booking_rental_price_per_day_gte_zero'), models.CheckConstraint(condition=models.Q(('booking_total_amount__gte', 0)), name='booking_total_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('booking_end_date__gte', models.F('booking_start_date'))), name='booking_end_date_gte_booking_start_date')],
            },
        ),
    ]
