# Generated by Django 6.0.3 on 2026-04-11 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='approved_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_identity_number',
            field=models.CharField(blank=True, help_text='Enter engine number, vehicle number, chassis number, or serial number.', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Identity number can contain letters, numbers, hyphen and slash only.', regex='^[A-Za-z0-9\\-/]+$')]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Owner name can contain letters, numbers, spaces, hyphen, &, (), / and dot only.', regex='^[A-Za-z0-9\\s\\-\\&\\(\\)\\/\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_category',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Power Tiller', 'Power Tiller'), ('Rotavator', 'Rotavator'), ('Cultivator', 'Cultivator'), ('Disc Harrow', 'Disc Harrow'), ('Plough', 'Plough'), ('Seed Drill', 'Seed Drill'), ('Planter', 'Planter'), ('Transplanter', 'Transplanter'), ('Sprayer', 'Sprayer'), ('Harvester', 'Harvester'), ('Reaper', 'Reaper'), ('Thresher', 'Thresher'), ('Baler', 'Baler'), ('Mulcher', 'Mulcher'), ('Subsoiler', 'Subsoiler'), ('Ridger', 'Ridger'), ('Land Leveler', 'Land Leveler'), ('Trailer', 'Trailer'), ('Pump Set', 'Pump Set')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='farmer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['owner_name'], name='equipment_r_owner_n_d9f0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_identity_number'], name='equipment_r_equipme_e984d7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['approval_status'], name='equipment_r_approva_54db83_idx'),
        ),
    ]
