# Generated by Django 6.0.3 on 2026-04-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0002_equipment_approval_status_equipment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
