# Generated by Django 6.0.3 on 2026-05-27 20:45

import django.db.models.deletion
import django.utils.timezone
import equipment_rental.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_rental', '0003_alter_equipment_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_farmer__f1e16f_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_equipme_413e79_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_custome_fe47d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_custome_764370_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_booking_f51dff_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_booking_7f809d_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_booking_d9deb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_payment_d1571b_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentbooking',
            name='equipment_r_booking_1cc2a1_idx',
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='payment_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('other', 'Other')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, validators=[equipment_rental.validators.validate_razorpay_order_id]),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/images/', validators=[equipment_rental.validators.validate_image_extension, equipment_rental.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[equipment_rental.validators.validate_positive_amount, equipment_rental.validators.validate_minimum_rental_price]),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='booking_created_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='booking_rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[equipment_rental.validators.validate_positive_amount]),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='booking_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[equipment_rental.validators.validate_positive_amount]),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_bookings', to='equipment_rental.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='payment_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay payment id.', max_length=100, null=True, validators=[equipment_rental.validators.validate_razorpay_payment_id]),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_active', 'approval_status', 'equipment_status'], name='equipment_r_is_acti_35fb84_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['farmer_user', 'booking_status'], name='equipment_r_farmer__9968a8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['equipment', 'booking_status'], name='equipment_r_equipme_b13691_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['equipment', 'booking_start_date', 'booking_end_date'], name='equipment_r_equipme_f18d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['payment_status', 'booking_status'], name='equipment_r_payment_c3c0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['booking_start_date', 'booking_end_date'], name='equipment_r_booking_e661fe_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbooking',
            index=models.Index(fields=['payment_paid_at'], name='equipment_r_payment_fdf61b_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_order_id__isnull', False)), fields=('razorpay_order_id',), name='unique_non_null_razorpay_order_id'),
        ),
        migrations.AddConstraint(
            model_name='equipmentbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_transaction_id__isnull', False)), fields=('payment_transaction_id',), name='unique_non_null_payment_transaction_id'),
        ),
    ]
