# Generated by Django 6.0.3 on 2026-04-22 20:11

import accounts.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[A-Za-z\\s]+$')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[A-Za-z\\s]+$')], verbose_name='Last Name')),
                ('username', models.CharField(db_index=True, help_text='Use lowercase letters and numbers only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain lowercase letters and numbers only.', regex='^[a-z0-9]+$')], verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('country_code', models.CharField(default='+91', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid country code like +91.', regex='^\\+\\d{1,4}$')], verbose_name='Country Code')),
                ('mobile_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('mr', 'Marathi'), ('hi', 'Hindi')], db_index=True, default='en', max_length=2, verbose_name='Language Preference')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], db_index=True, max_length=20, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_secret_code', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Admin secret code can contain letters, numbers, @, #, _, and - only.', regex='^[A-Za-z0-9@#_\\-]+$')], verbose_name='Admin Secret Code')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('village', models.CharField(db_index=True, max_length=100, verbose_name='Village')),
                ('taluka', models.CharField(db_index=True, max_length=100, verbose_name='Taluka')),
                ('district', models.CharField(db_index=True, max_length=100, verbose_name='District')),
                ('state', models.CharField(db_index=True, max_length=100, verbose_name='State')),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode.', regex='^\\d{6}$')], verbose_name='Pincode')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('mobile_number', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('email_otp', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='Email OTP')),
                ('mobile_otp', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='Mobile OTP')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='Mobile Verified')),
                ('expires_at', models.DateTimeField(default=accounts.models.default_otp_expiry, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_ot_email_b57695_idx'), models.Index(fields=['mobile_number'], name='accounts_ot_mobile__bb82ec_idx'), models.Index(fields=['is_email_verified'], name='accounts_ot_is_emai_1a4ab1_idx'), models.Index(fields=['is_mobile_verified'], name='accounts_ot_is_mobi_93f527_idx'), models.Index(fields=['created_at'], name='accounts_ot_created_dffff8_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_b7415d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mobile_number'], name='accounts_cu_mobile__596ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['language_preference'], name='accounts_cu_languag_b02933_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_fcefff_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['created_at'], name='accounts_ad_created_9b7f64_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['village'], name='accounts_fa_village_efd522_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['taluka'], name='accounts_fa_taluka_eb02ca_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['district'], name='accounts_fa_distric_562d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['state'], name='accounts_fa_state_a03746_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['pincode'], name='accounts_fa_pincode_0d2c09_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerprofile',
            index=models.Index(fields=['created_at'], name='accounts_fa_created_dc63f8_idx'),
        ),
    ]
