# Generated by Django 6.0.3 on 2026-04-23 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
    ]
