# Generated by Django 6.0.3 on 2026-04-23 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.UniqueConstraint(fields=('email', 'mobile_number'), name='unique_otp_email_mobile'),
        ),
    ]
