# Generated by Django 6.0.3 on 2026-04-28 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otpverification',
            name='unique_otp_email_mobile',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='OTP Verified'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('general', 'General'), ('registration', 'Registration'), ('forgot_password', 'Forgot Password'), ('update_email', 'Update Email'), ('update_mobile', 'Update Mobile'), ('update_profile', 'Update Profile')], db_index=True, default='general', max_length=50, verbose_name='OTP Purpose'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='Email OTP'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='Mobile OTP'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['purpose'], name='accounts_ot_purpose_eca24e_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['is_verified'], name='accounts_ot_is_veri_b0bb34_idx'),
        ),
    ]
