# Generated by Django 6.0.2 on 2026-04-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('soil_n', models.FloatField()),
                ('soil_p', models.FloatField()),
                ('soil_k', models.FloatField()),
                ('soil_color', models.CharField(max_length=50)),
                ('ph', models.FloatField()),
                ('recommended_fertilizers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
