# Generated by Django 6.0.3 on 2026-04-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FertilizerRecommendationLog',
        ),
    ]
