# Generated by Django 6.0.3 on 2026-05-07 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fertilizer', '0002_delete_fertilizerrecommendationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], db_index=True, max_length=20)),
                ('crop', models.CharField(choices=[('Cotton', 'Cotton'), ('Ginger', 'Ginger'), ('Gram', 'Gram'), ('Grapes', 'Grapes'), ('Groundnut', 'Groundnut'), ('Jowar', 'Jowar'), ('Maize', 'Maize'), ('Masoor', 'Masoor'), ('Moong', 'Moong'), ('Rice', 'Rice'), ('Soybean', 'Soybean'), ('Sugarcane', 'Sugarcane'), ('Tur', 'Tur'), ('Turmeric', 'Turmeric'), ('Urad', 'Urad'), ('Wheat', 'Wheat')], db_index=True, max_length=100)),
                ('soil_color', models.CharField(choices=[('Black', 'Black'), ('Dark Brown', 'Dark Brown'), ('Light Brown', 'Light Brown'), ('Medium Brown', 'Medium Brown'), ('Red', 'Red'), ('Reddish Brown', 'Reddish Brown')], db_index=True, max_length=100)),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph', models.FloatField(verbose_name='pH')),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('recommendation_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fertilizer Recommendation History',
                'verbose_name_plural': 'Fertilizer Recommendation Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='fertilizer__user_id_c2645c_idx'), models.Index(fields=['user_type'], name='fertilizer__user_ty_7da4d6_idx'), models.Index(fields=['crop'], name='fertilizer__crop_625920_idx'), models.Index(fields=['soil_color'], name='fertilizer__soil_co_496983_idx'), models.Index(fields=['created_at'], name='fertilizer__created_fbc156_idx'), models.Index(fields=['updated_at'], name='fertilizer__updated_9cc2eb_idx'), models.Index(fields=['user_type', 'crop'], name='fertilizer__user_ty_3b2e94_idx'), models.Index(fields=['user', 'created_at'], name='fertilizer__user_id_531115_idx'), models.Index(fields=['crop', 'soil_color'], name='fertilizer__crop_a1927e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nitrogen__gte', 0)), name='fertilizer_history_nitrogen_gte_0'), models.CheckConstraint(condition=models.Q(('phosphorus__gte', 0)), name='fertilizer_history_phosphorus_gte_0'), models.CheckConstraint(condition=models.Q(('potassium__gte', 0)), name='fertilizer_history_potassium_gte_0'), models.CheckConstraint(condition=models.Q(('ph__gte', 0), ('ph__lte', 14)), name='fertilizer_history_ph_between_0_14'), models.CheckConstraint(condition=models.Q(('rainfall__gte', 0)), name='fertilizer_history_rainfall_gte_0'), models.CheckConstraint(condition=models.Q(('temperature__gte', -50), ('temperature__lte', 100)), name='fertilizer_history_temperature_valid_range')],
            },
        ),
    ]
