# Generated by Django 6.0.3 on 2026-04-11 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200)),
                ('scheme_code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Scheme code must contain only uppercase letters, numbers, underscore, or hyphen.', regex='^[A-Z0-9_-]+$')])),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('loan', 'Loan'), ('subsidy', 'Subsidy'), ('grant', 'Grant'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('official_link', models.URLField(blank=True, null=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('scheme_image', models.ImageField(blank=True, null=True, upload_to='government_schemes/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('scheme_document', models.FileField(blank=True, null=True, upload_to='government_schemes/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^[0-9+\\- ]{8,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scheme_code'], name='government__scheme__bb7e07_idx'), models.Index(fields=['slug'], name='government__slug_6b045d_idx'), models.Index(fields=['category'], name='government__categor_c1f963_idx'), models.Index(fields=['status'], name='government__status_f9e530_idx'), models.Index(fields=['is_featured'], name='government__is_feat_02ecb1_idx'), models.Index(fields=['start_date'], name='government__start_d_d56831_idx'), models.Index(fields=['end_date'], name='government__end_dat_f69611_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='government_scheme_end_date_gte_start_date')],
            },
        ),
    ]
