# Generated by Django 6.0.3 on 2026-05-07 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('loan', 'Loan'), ('subsidy', 'Subsidy'), ('grant', 'Grant'), ('insurance', 'Insurance'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='scheme_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Scheme code must contain only uppercase letters, numbers, underscore, or hyphen.', regex='^[A-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['category', 'status'], name='government__categor_30295e_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['status', 'is_featured'], name='government__status_2ce9a1_idx'),
        ),
    ]
