# Generated by Django 6.0.3 on 2026-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseprediction',
            name='crop_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='disease_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='suggestion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
